services:
  nats:
    image: nats:latest
    command:
    - --http_port=8222
    - --jetstream  # JetStream enable
    - -sd=/data    # JetStream store
    ports:
      - 4222:4222  # NATS clients
      - 8222:8222  # monitoring
    volumes:
      - nats_data:/data
    networks:
    - nats

  # See: easily add nodes to a cluster:
  #   https://docs.nats.io/running-a-nats-service/nats_docker
  # nats:
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  # nats-1:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]
  # nats-2:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]

networks:
  nats:
    name: nats

volumes:
  nats_data:
    name: nats_data
