services:
  nats:
    image: nats:latest
    command:
    - -c=/nats-server.conf
    - --http_port=8222
    - --jetstream  # JetStream enable
    - -sd=/data    # JetStream store
    ports:
      - 4222:4222  # NATS clients
      - 8222:8222  # monitoring
      - 1883:1883  # MQTT
    volumes:
      - nats_data:/data
      # Choose one:
      - ./nats-server.conf:/nats-server.conf
      # - ./nats-server-jwt.conf:/nats-server.conf
    networks:
    - nats

  natsbox:
    image: natsio/nats-box:latest
    tty: true
    restart: no
    profiles:
    - oneoff
    depends_on:
    - nats
    networks:
    - nats
    environment:
      # NATS_URL: nats://sys:admin@nats:4222/
      NATS_URL: nats://app_admin:admin@nats:4222/

  # See: easily add nodes to a cluster:
  #   https://docs.nats.io/running-a-nats-service/nats_docker
  # nats:
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  # nats-1:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]
  # nats-2:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]

networks:
  nats:
    name: nats

volumes:
  nats_data:
    name: nats_data
