default_context:
  project_name: 'fastestapi'
  project_slug: 'fastestapi'
  domain_main: 'fastestapi.com'
  domain_staging: 'stag.fastestapi.com'
  docker_swarm_stack_name_main: 'fastestapi-com'
  docker_swarm_stack_name_staging: 'stag-fastestapi-com'
  secret_key: '9a4ae7f654b85ec9a3523a8dac6d0f1eac0066f1521b125bde843ccd522e3fb3'
  first_superuser: 'kolypto@gmail.com'
  first_superuser_password: 's3cur1ty'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastestapi.com", "https://stag.fastestapi.com", "https://fastestapi.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastestapi.com'
  postgres_password: 'pass'
  pgadmin_default_user: 'kolypto@gmail.com'
  pgadmin_default_user_password: 's3cur1ty'
  traefik_constraint_tag: 'fastestapi.com'
  traefik_constraint_tag_staging: 'stag.fastestapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:s3cur1ty'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
