version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: play_go_postgres
    command: -p 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '127.0.0.1:5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
