all:

CC=gcc -no-pie -g

01-helloworld: 01-helloworld.s
	@${CC} $< -o $@

03-asm-commands: 03-asm-commands.s
	@${CC} $< -o $@

04-asm-printf: 04-asm-printf.s
	@${CC} $< -o $@

05-subprog: 05-subprog.s
	@${CC} $< -o $@

06-stat: 06-stat.S
	@${CC} $< -o $@

07-lods: 07-lods.S
	@${CC} $< -o $@

