services:
  openfga:
    image: openfga/openfga
    # Default: no auth
    ports:
    - 8080:8080  # HTTP
    - 8081:8081  # gRPC
    - 2112:2112  # Prometheus metrics
    - 4317:4317  # Tracing
    - 3000:3000  # Playground
    command:
    - run
    - --trace-enabled=true
    networks:
    - openfga

networks:
  openfga:
    name: openfga
