[package]
name = "a18-async-await"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
regex = "1.12.2"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["fs", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.17"
