version: '3'

services:

  # Edge router
  # This is the only container that has published ports.
  traefik:
    image: traefik:v2.9

    ports:
      # Incoming requests
      - "80:80"
      # Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # HUB
      - "8000:8000"
      - "9900:9900"

    # Listed to Docker.
    # Enable Web UI (port 8080)
    # Enable experimental HUB (port 9900)
    command: >
      --providers.docker --api.insecure=true 
      --experimental.hub --hub.tls.insecure --metrics.prometheus.addrouterslabels

    volumes:
      # Listen to Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock


  # Services

  # Whoami: 
  #   When Host = whoami.localhost
  #   Echo IP address
  whoami:
    # Whoami: shows its IP address
    image: traefik/whoami
    labels:
      # Define: http.router: name="whoami"
      # Rule: Hostname match: "whoami.localhost"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
