// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbs

import (
	"database/sql"
)

type Article struct {
	ID       int64          `db:"id" json:"id"`
	AuthorID int64          `db:"author_id" json:"author_id"`
	Title    string         `db:"title" json:"title"`
	Body     sql.NullString `db:"body" json:"body"`
}

type User struct {
	ID    int64         `db:"id" json:"id"`
	Login string        `db:"login" json:"login"`
	Age   sql.NullInt32 `db:"age" json:"age"`
}
