input:
  # read from stdin
  stdin: {}

pipeline:
  # Procesors applied to *all* messages
  processors:
    - mapping: root = content().uppercase()

output:
  # write to stdout immediately
  # useful for testing processors
  stdout: {}
