// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BarticleTags string
	Barticles    string
	Btags        string
	Busers       string
}{
	BarticleTags: "barticle_tags",
	Barticles:    "barticles",
	Btags:        "btags",
	Busers:       "busers",
}
