// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBtags(t *testing.T) {
	t.Parallel()

	query := Btags()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBtagsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBtagsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Btags().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBtagsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BtagSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBtagsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BtagExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Btag exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BtagExists to return true, but got false.")
	}
}

func testBtagsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	btagFound, err := FindBtag(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if btagFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBtagsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Btags().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBtagsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Btags().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBtagsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	btagOne := &Btag{}
	btagTwo := &Btag{}
	if err = randomize.Struct(seed, btagOne, btagDBTypes, false, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}
	if err = randomize.Struct(seed, btagTwo, btagDBTypes, false, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = btagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = btagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Btags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBtagsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	btagOne := &Btag{}
	btagTwo := &Btag{}
	if err = randomize.Struct(seed, btagOne, btagDBTypes, false, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}
	if err = randomize.Struct(seed, btagTwo, btagDBTypes, false, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = btagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = btagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func btagBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func btagAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Btag) error {
	*o = Btag{}
	return nil
}

func testBtagsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Btag{}
	o := &Btag{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, btagDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Btag object: %s", err)
	}

	AddBtagHook(boil.BeforeInsertHook, btagBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	btagBeforeInsertHooks = []BtagHook{}

	AddBtagHook(boil.AfterInsertHook, btagAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	btagAfterInsertHooks = []BtagHook{}

	AddBtagHook(boil.AfterSelectHook, btagAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	btagAfterSelectHooks = []BtagHook{}

	AddBtagHook(boil.BeforeUpdateHook, btagBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	btagBeforeUpdateHooks = []BtagHook{}

	AddBtagHook(boil.AfterUpdateHook, btagAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	btagAfterUpdateHooks = []BtagHook{}

	AddBtagHook(boil.BeforeDeleteHook, btagBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	btagBeforeDeleteHooks = []BtagHook{}

	AddBtagHook(boil.AfterDeleteHook, btagAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	btagAfterDeleteHooks = []BtagHook{}

	AddBtagHook(boil.BeforeUpsertHook, btagBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	btagBeforeUpsertHooks = []BtagHook{}

	AddBtagHook(boil.AfterUpsertHook, btagAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	btagAfterUpsertHooks = []BtagHook{}
}

func testBtagsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBtagsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(btagColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBtagToManyArticleBarticles(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Btag
	var b, c Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, articleDBTypes, false, articleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, articleDBTypes, false, articleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into \"barticle_tags\" (\"tag_id\", \"article_id\") values ($1, $2)", a.ID, b.ID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into \"barticle_tags\" (\"tag_id\", \"article_id\") values ($1, $2)", a.ID, c.ID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.ArticleBarticles().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ID == b.ID {
			bFound = true
		}
		if v.ID == c.ID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BtagSlice{&a}
	if err = a.L.LoadArticleBarticles(ctx, tx, false, (*[]*Btag)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ArticleBarticles); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.ArticleBarticles = nil
	if err = a.L.LoadArticleBarticles(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ArticleBarticles); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBtagToManyAddOpArticleBarticles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Btag
	var b, c, d, e Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, btagDBTypes, false, strmangle.SetComplement(btagPrimaryKeyColumns, btagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Article{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Article{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddArticleBarticles(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.TagBtags[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.TagBtags[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.ArticleBarticles[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.ArticleBarticles[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.ArticleBarticles().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testBtagToManySetOpArticleBarticles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Btag
	var b, c, d, e Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, btagDBTypes, false, strmangle.SetComplement(btagPrimaryKeyColumns, btagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Article{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetArticleBarticles(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.ArticleBarticles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetArticleBarticles(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.ArticleBarticles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.TagBtags) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.TagBtags) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.TagBtags[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.TagBtags[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.ArticleBarticles[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.ArticleBarticles[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testBtagToManyRemoveOpArticleBarticles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Btag
	var b, c, d, e Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, btagDBTypes, false, strmangle.SetComplement(btagPrimaryKeyColumns, btagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Article{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddArticleBarticles(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.ArticleBarticles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveArticleBarticles(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.ArticleBarticles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.TagBtags) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.TagBtags) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.TagBtags[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.TagBtags[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.ArticleBarticles) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.ArticleBarticles[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.ArticleBarticles[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testBtagsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBtagsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BtagSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBtagsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Btags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	btagDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`}
	_           = bytes.MinRead
)

func testBtagsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(btagPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(btagAllColumns) == len(btagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, btagDBTypes, true, btagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBtagsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(btagAllColumns) == len(btagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Btag{}
	if err = randomize.Struct(seed, o, btagDBTypes, true, btagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, btagDBTypes, true, btagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(btagAllColumns, btagPrimaryKeyColumns) {
		fields = btagAllColumns
	} else {
		fields = strmangle.SetComplement(
			btagAllColumns,
			btagPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BtagSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBtagsUpsert(t *testing.T) {
	t.Parallel()

	if len(btagAllColumns) == len(btagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Btag{}
	if err = randomize.Struct(seed, &o, btagDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Btag: %s", err)
	}

	count, err := Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, btagDBTypes, false, btagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Btag struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Btag: %s", err)
	}

	count, err = Btags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
